# Introduction to tensorflow

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function ( a way to speed up our regular python functions )
* Using GPUs with Tensorflow (or TPUs)




## Introduction to Tensors

In [1]:
# Importing tensorflow as tf in a conventional way
import tensorflow as tf

In [2]:
# printing the tensorflow version
print(tf.__version__)

2.17.0


In [3]:
# Getting my hands dirty with tensorflow tf.constant function
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Vectors are one dimensional in nature representing magnitude and direction (For example: wind with x speed in y direction)

In [8]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# matrixes are 2-dimensional tensors while vectors are 1-dimensional tensors
another_matrix = tf.constant([[1.,2.,3.],[2.,1.,4.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [2., 1., 4.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Introducing tensors, a ndimensional representation
tensors = tf.constant([[[1,2,3],[2,3,4]],[[4,5,6],[6,7,8]],[[8,9,10],[10,11,12]]])
tensors

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 8,  9, 10],
        [10, 11, 12]]], dtype=int32)>

In [13]:
tensors.ndim

3

## Creating tensors with tf.Variables

In [14]:
# creating the same tensors with tf.Variables for above
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
# Trying to change one of the element in changable tensor
changable_tensor[0].assign(2)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 7], dtype=int32)>

## Creating random tensors

In [16]:
# Random tensors are tensors of some abitary size with random numbers.
random_1 = tf.random.Generator.from_seed(42) # set seed for redproducibility
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [17]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in the order

In [18]:
# Shuffle a tensor ( valuable for shuffle our data for making it appropriate for training the deep learning mode)
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [19]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [20]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

## Creating tensors from NumPy arrays

In [21]:
# creating all the tensors with one with given shape
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## We can also turn numpy arrays into tensors

* The key difference between numpy and tensors are tensors can be reun on a GPU much quicker for computing


In [23]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# x = tf.constant(some_matrix)
# y = tf.constant(vector)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape = (2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting Information from tensors

When dealing with tensors we probably want to be aware of these properties

* Shape
* Rank
* Axis or dimension
* Size

In [25]:
# Creating a rank 4 tensors ( 4 dimensions )
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor.ndim

4

In [27]:
# indexing into rand_4_tensor
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [28]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# Get various attributes of our tensors
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements inside our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements inside our tensor: 120


 ## Indexing tensors

 Tensors can be indexed just like pythons lists

In [30]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [31]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [32]:
# Creating a rank 2 tensors and adding an extra dimension
rank_2_tensors = tf.ones(shape=(2,2))
rank_2_tensors

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [33]:
# Getting the last item of each of our rank 2 tensors
rank_2_tensors[:,-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [34]:
# Adding extra dimension to our rank 2 tensors

rank_3_tensors = rank_2_tensors[...,tf.newaxis]
rank_3_tensors

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [35]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensors,axis=-1) # -1 means expand from the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[1.],
        [1.]],

       [[1.],
        [1.]]], dtype=float32)>

In [36]:
tf.expand_dims(rank_2_tensors,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]]], dtype=float32)>

## Manipulating tensors (Tensors Operations)

In [37]:
# Basic operations `+`,`-`,`*`,`/`
tensor = tf.constant([[10,7],[3,4]]) # matrix addition
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [38]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
# Mutiplication also works
tensor * 10
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [40]:
# Operation using tensorflow functions

tf.multiply(tensor,10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [41]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

## Matrix multiplication

* In machine learning, matrix muliplication is super important

In [42]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [43]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [44]:
# Matrix multiplication with python operator "@"
tensorA = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensorB = tf.constant([[3,5],[6,7],[1,8]])
tensorA @ tensorB

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [45]:
tensorA.shape

TensorShape([3, 3])

In [46]:
tensorB.ndim

2

In [47]:
# Creating a tensor (3,2) tensor
X = tf.constant([[1,2],[3,4],[5,6]])

# Creating another (3,2) tensor

Y = tf.constant([[7,8],[9,10],[11,12]])

X,Y


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

## Try to matrix multiplying tensor of same shape

Two rules of matrix multiplication

* The inner dimension of matrix should be matched
* The resulting matrix has the shape of outer dimension

In [48]:
Y = tf.reshape(Y,shape=(2,3))

In [49]:
X @ Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
# Doing samething with transpose
X
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [51]:
# Transpose flips the axis where as reshape randomly shuffels the tensor to the given space

## The dot product

Matrix multiplication is also reffered to as the dot product

* tf.matmul()
* tf.tensordot()

In [52]:
# Perform the dot product on X and Y ( requires X or Y to be transposed)
X, Y
tf.tensordot(tf.transpose(X),tf.transpose(Y),axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 103],
       [100, 136]], dtype=int32)>

In [53]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [54]:
Y = tf.transpose(Y)

In [55]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 8, 11],
        [ 9, 12]], dtype=int32)>)

In [56]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 29,  28,  32],
       [ 65,  66,  72],
       [101, 104, 112]], dtype=int32)>

In [57]:
# Generally performing matrix multiplication in two of the matrix, we need to either transpose or reshape for satisfying the rule


## Changing datatype of a Tensor

In [58]:
# Creating a new tensor with default data-type which is float 32
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [59]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [60]:
B = tf.constant([1.7,7.4],dtype=tf.float16)
B.dtype

tf.float16

In [61]:
C = tf.cast(C,dtype=tf.int16)
C.dtype

tf.int16

## Aggregating tensor

Aggregating tensor = condensing them from multiple values down to a smaller amount of values

In [62]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [63]:
# Getting absoulte value from the above tensor
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

## Let's go through the following forms of aggregations
* Get the minimum
* Get maximum
* Get the mean of tensor
* Get the sum of tensor

In [64]:
# Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([74, 53, 49, 75, 75, 43, 60, 10, 23, 30, 13, 15, 64, 32, 15, 55, 96,
       38, 21, 23, 47, 14, 93, 82, 88, 91,  4, 24, 30, 73,  9, 55, 76, 84,
       75, 29, 83, 46,  1, 78, 78, 78, 99, 28, 98, 37, 79, 61, 82, 47])>

In [65]:
tf.size(E).numpy()

50

In [66]:
E.shape

TensorShape([50])

In [67]:
tf.reduce_min(E).numpy()

1

In [68]:
tf.reduce_max(E).numpy()

99

In [69]:
# Finding the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [70]:
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=int64, numpy=2633>

In [71]:
x = tf.constant([[1., 2.], [3., 4.]])
tf.math.reduce_variance(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.25>

In [72]:
tf.math.reduce_std(x)

<tf.Tensor: shape=(), dtype=float32, numpy=1.1180339>

In [73]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.772633>

## Finding positional maximum and minumum of a tensor (argmin and argmax)

In [74]:
# Creating a new tensor for finding potential maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [76]:
# Index on the largest position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [77]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [78]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [79]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (removing all single dimensions)

In [80]:
# Create a tensor to get starteed
tf.random.set_seed(42)
some_tensor = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
some_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [81]:
some_tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [82]:
some_tensor = tf.squeeze(some_tensor)
some_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

## One-hot Encode

In [83]:
# creating a list of indices
some_list = [0,1,2,3]
# One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [84]:
tf.one_hot(some_list,depth=4,on_value="yes",off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

In [85]:
tf.one_hot(some_list,depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [86]:
tf.one_hot(some_list,depth=5,on_value="yes",off_value="no")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no', b'no'],
       [b'no', b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'no', b'yes', b'no']], dtype=object)>

## Squaring, Log, square root

In [87]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [88]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [89]:
# Finding the square root
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [90]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and numpy

TensorFlow interacts beautifully with numPy arrays

In [91]:
# Create a tensor directly from a numpy array
J = tf.constant(np.array([3.,7.,10.]))

In [92]:
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [93]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [94]:
## Finding access to GPUs

In [95]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [96]:
!nvidia-smi

Sun Sep 15 16:14:30 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P0              25W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [97]:
## If we have access to CUDA-enabled GPT, Tensoflow will automatically use it